// ============================================================
//  panneaux_data.js  –  Base de données des panneaux routiers
//  Auto-École Marti
//  Source : Liste complète des signaux routiers réglementaires
//           CEREMA / Instruction Interministérielle sur la
//           Signalisation Routière (IISR) – édition juin 2009
// ============================================================

const panneauxData = [

  // ── FAMILLE A : DANGER (Triangle rouge) ──────────────────────────

  { code: "A1a",  categorie: "danger", nom: "Virage à droite",                          description: "Annonce un virage à droite.", type: "virage" },
  { code: "A1b",  categorie: "danger", nom: "Virage à gauche",                          description: "Annonce un virage à gauche.", type: "virage" },
  { code: "A1c",  categorie: "danger", nom: "Succession de virages, le premier à droite", description: "Annonce une succession de virages dont le premier est à droite.", type: "virage" },
  { code: "A1d",  categorie: "danger", nom: "Succession de virages, le premier à gauche", description: "Annonce une succession de virages dont le premier est à gauche.", type: "virage" },
  { code: "A2a",  categorie: "danger", nom: "Cassis ou dos-d'âne",                      description: "Annonce un cassis (dépression transversale) ou un dos-d'âne sur la chaussée.", type: "relief" },
  { code: "A2b",  categorie: "danger", nom: "Ralentisseur de type dos-d'âne",           description: "Annonce un ralentisseur de type dos-d'âne.", type: "relief" },
  { code: "A3",   categorie: "danger", nom: "Chaussée rétrécie",                        description: "Annonce un rétrécissement de la chaussée (des deux côtés ou sans précision).", type: "chaussée" },
  { code: "A3a",  categorie: "danger", nom: "Chaussée rétrécie par la droite",          description: "Annonce un rétrécissement de la chaussée du côté droit.", type: "chaussée" },
  { code: "A3b",  categorie: "danger", nom: "Chaussée rétrécie par la gauche",          description: "Annonce un rétrécissement de la chaussée du côté gauche.", type: "chaussée" },
  { code: "A4",   categorie: "danger", nom: "Chaussée particulièrement glissante",      description: "Annonce une portion de route particulièrement glissante (verglas, boue, gravillons…).", type: "météo" },
  { code: "A6",   categorie: "danger", nom: "Pont mobile",                              description: "Annonce un pont mobile pouvant s'ouvrir pour laisser passer des embarcations.", type: "ouvrage" },
  { code: "A7",   categorie: "danger", nom: "Passage à niveau avec barrières manuelles", description: "Annonce un passage à niveau muni de barrières à fonctionnement manuel lors du passage des trains.", type: "passage_niveau" },
  { code: "A8",   categorie: "danger", nom: "Passage à niveau sans barrières ni demi-barrières", description: "Annonce un passage à niveau sans barrières ni demi-barrières.", type: "passage_niveau" },
  { code: "A9",   categorie: "danger", nom: "Traversée de voies de tramways",           description: "Annonce une traversée de voies de tramways.", type: "tramway" },
  { code: "A13a", categorie: "danger", nom: "Endroit fréquenté par les enfants",        description: "Annonce un endroit fréquenté par les enfants (école, terrain de jeux…).", type: "piétons" },
  { code: "A13b", categorie: "danger", nom: "Passage pour piétons",                     description: "Annonce un passage pour piétons.", type: "piétons" },
  { code: "A14",  categorie: "danger", nom: "Autres dangers",                           description: "Annonce un danger dont la nature peut être précisée par un panonceau.", type: "divers" },
  { code: "A15a1",categorie: "danger", nom: "Passage d'animaux domestiques",            description: "Annonce la traversée possible d'animaux domestiques (variante 1).", type: "animaux" },
  { code: "A15a2",categorie: "danger", nom: "Passage d'animaux domestiques (variante)", description: "Annonce la traversée possible d'animaux domestiques (variante 2).", type: "animaux" },
  { code: "A15b", categorie: "danger", nom: "Passage d'animaux sauvages",               description: "Annonce la traversée possible d'animaux sauvages.", type: "animaux" },
  { code: "A15c", categorie: "danger", nom: "Passage de cavaliers",                     description: "Annonce la traversée possible de cavaliers.", type: "animaux" },
  { code: "A16",  categorie: "danger", nom: "Descente dangereuse",                      description: "Annonce une descente dangereuse. Le pourcentage de pente peut être indiqué.", type: "relief" },
  { code: "A17",  categorie: "danger", nom: "Annonce de feux tricolores",               description: "Annonce des feux tricolores à proximité.", type: "feux" },
  { code: "A18",  categorie: "danger", nom: "Circulation dans les deux sens",           description: "Annonce une section où la circulation se fait dans les deux sens (après une section à sens unique).", type: "circulation" },
  { code: "A19",  categorie: "danger", nom: "Risque de chute de pierres",               description: "Annonce un risque de chute de pierres ou de présence sur la route de pierres tombées.", type: "divers" },
  { code: "A20",  categorie: "danger", nom: "Débouché sur un quai ou une berge",        description: "Annonce un débouché sur un quai ou une berge (risque de chute dans l'eau).", type: "divers" },
  { code: "A21",  categorie: "danger", nom: "Débouché de cyclistes",                    description: "Annonce un débouché de cyclistes venant de droite ou de gauche.", type: "piétons" },
  { code: "A23",  categorie: "danger", nom: "Traversée d'une aire de danger aérien",   description: "Annonce la traversée d'une aire de danger aérien (survol d'avions à basse altitude).", type: "divers" },
  { code: "A24",  categorie: "danger", nom: "Vent latéral",                             description: "Annonce des risques de vent latéral violent pouvant déstabiliser les véhicules.", type: "météo" },

  // ── FAMILLE AB : PRIORITÉ AUX INTERSECTIONS ──────────────────────
  // Panneaux signalant les règles de priorité à l'intersection.

  { code: "AB1",  categorie: "priorite", nom: "Cédez le passage aux véhicules venant de droite", description: "Intersection où le conducteur est tenu de céder le passage aux véhicules débouchant de la ou des routes situées à sa droite.", type: "intersection" },
  { code: "AB2",  categorie: "priorite", nom: "Intersection avec route non prioritaire",          description: "Intersection avec une route dont les usagers doivent céder le passage (quand un panneau AB6 ne peut être utilisé).", type: "intersection" },
  { code: "AB3a", categorie: "priorite", nom: "Cédez le passage à l'intersection (signal de position)", description: "Signal de position indiquant l'obligation de céder le passage à l'intersection.", type: "priorite_absolue" },
  { code: "AB3b", categorie: "priorite", nom: "Cédez le passage à l'intersection (signal avancé)", description: "Signal avancé de l'AB3a annonçant l'obligation de céder le passage.", type: "priorite_absolue" },
  { code: "AB4",  categorie: "priorite", nom: "Stop (signal de position)",                        description: "Arrêt absolu obligatoire à l'intersection. Signal de position placé au niveau de la ligne de feu.", type: "priorite_absolue" },
  { code: "AB5",  categorie: "priorite", nom: "Stop (signal avancé)",                             description: "Signal avancé du panneau AB4 annonçant l'obligation de marquer l'arrêt.", type: "priorite_absolue" },
  { code: "AB6",  categorie: "priorite", nom: "Route prioritaire",                                description: "Indique le caractère prioritaire de la route sur laquelle il est implanté.", type: "intersection" },
  { code: "AB7",  categorie: "priorite", nom: "Fin de route prioritaire",                         description: "Signale la fin du caractère prioritaire de la route.", type: "intersection" },
  { code: "AB25", categorie: "priorite", nom: "Carrefour à sens giratoire",                       description: "Annonce un carrefour à sens giratoire (rond-point). Les véhicules engagés sont prioritaires.", type: "intersection" },

  // ── FAMILLE B : PRESCRIPTION (Interdictions, Obligations, Fins) ──
  // Panneaux ronds. Rouge/blanc = interdiction. Bleu = obligation.
  // Barré = fin de prescription.

  // Interdictions d'accès et de circulation
  { code: "B0",   categorie: "interdiction", nom: "Circulation interdite dans les deux sens",     description: "Interdit toute circulation dans les deux sens.", type: "acces" },
  { code: "B1",   categorie: "interdiction", nom: "Sens interdit",                                description: "Interdit l'accès à tout véhicule dans ce sens.", type: "acces" },
  { code: "B2a",  categorie: "interdiction", nom: "Interdiction de tourner à gauche",             description: "Interdit de tourner à gauche à la prochaine intersection.", type: "direction" },
  { code: "B2b",  categorie: "interdiction", nom: "Interdiction de tourner à droite",             description: "Interdit de tourner à droite à la prochaine intersection.", type: "direction" },
  { code: "B2c",  categorie: "interdiction", nom: "Interdiction de faire demi-tour",              description: "Interdit de faire demi-tour jusqu'à la prochaine intersection.", type: "direction" },
  { code: "B3",   categorie: "interdiction", nom: "Interdiction de dépasser",                     description: "Interdit de dépasser tous les véhicules à moteur autres que ceux à deux roues sans side-car.", type: "depassement" },
  { code: "B3a",  categorie: "interdiction", nom: "Interdiction de dépasser pour les poids lourds", description: "Interdit aux véhicules de transport de marchandises de plus de 3,5 t de dépasser.", type: "depassement" },
  { code: "B4",   categorie: "interdiction", nom: "Arrêt au poste de douane",                     description: "Arrêt obligatoire au poste de douane.", type: "acces" },
  { code: "B5a",  categorie: "interdiction", nom: "Arrêt au poste de gendarmerie",                description: "Arrêt obligatoire au poste de gendarmerie.", type: "acces" },
  { code: "B5b",  categorie: "interdiction", nom: "Arrêt au poste de police",                     description: "Arrêt obligatoire au poste de police.", type: "acces" },
  { code: "B5c",  categorie: "interdiction", nom: "Arrêt au poste de péage",                      description: "Arrêt obligatoire au poste de péage.", type: "acces" },

  // Stationnement
  { code: "B6a1", categorie: "interdiction", nom: "Stationnement interdit",                       description: "Interdit de stationner. L'arrêt bref pour prendre ou déposer un passager est autorisé.", type: "stationnement" },
  { code: "B6a2", categorie: "interdiction", nom: "Stationnement interdit du 1er au 15 du mois",  description: "Interdit de stationner du 1er au 15 du mois (stationnement unilatéral alterné).", type: "stationnement" },
  { code: "B6a3", categorie: "interdiction", nom: "Stationnement interdit du 16 à la fin du mois", description: "Interdit de stationner du 16 à la fin du mois (stationnement unilatéral alterné).", type: "stationnement" },
  { code: "B6b1", categorie: "interdiction", nom: "Entrée de zone à stationnement interdit",      description: "Signale l'entrée d'une zone où le stationnement est interdit.", type: "stationnement" },
  { code: "B6b2", categorie: "interdiction", nom: "Entrée de zone à stationnement unilatéral alterné", description: "Entrée d'une zone à stationnement unilatéral à alternance semi-mensuelle.", type: "stationnement" },
  { code: "B6b3", categorie: "interdiction", nom: "Entrée de zone à stationnement limité (disque)", description: "Entrée d'une zone à stationnement de durée limitée avec contrôle par disque.", type: "stationnement" },
  { code: "B6b4", categorie: "interdiction", nom: "Entrée de zone à stationnement payant",        description: "Entrée d'une zone à stationnement payant.", type: "stationnement" },
  { code: "B6b5", categorie: "interdiction", nom: "Entrée de zone à stationnement unilatéral alterné et limité", description: "Entrée d'une zone à stationnement unilatéral à alternance semi-mensuelle et à durée limitée avec disque.", type: "stationnement" },
  { code: "B6d",  categorie: "interdiction", nom: "Arrêt et stationnement interdits",             description: "Interdit tout arrêt et tout stationnement, même momentané.", type: "stationnement" },

  // Accès interdit à certains véhicules
  { code: "B7a",  categorie: "interdiction", nom: "Accès interdit aux véhicules à moteur sauf cyclomoteurs", description: "Interdit l'accès aux véhicules à moteur à l'exception des cyclomoteurs.", type: "acces" },
  { code: "B7b",  categorie: "interdiction", nom: "Accès interdit à tous les véhicules à moteur", description: "Interdit l'accès à tous les véhicules à moteur.", type: "acces" },
  { code: "B8",   categorie: "interdiction", nom: "Accès interdit aux véhicules de transport de marchandises", description: "Interdit l'accès aux véhicules affectés au transport de marchandises.", type: "acces" },
  { code: "B9a",  categorie: "interdiction", nom: "Accès interdit aux piétons",                  description: "Interdit l'accès aux piétons.", type: "acces" },
  { code: "B9b",  categorie: "interdiction", nom: "Accès interdit aux cycles",                    description: "Interdit l'accès aux bicyclettes et cycles.", type: "acces" },
  { code: "B9c",  categorie: "interdiction", nom: "Accès interdit aux véhicules à traction animale", description: "Interdit l'accès aux véhicules à traction animale.", type: "acces" },
  { code: "B9d",  categorie: "interdiction", nom: "Accès interdit aux véhicules agricoles à moteur", description: "Interdit l'accès aux véhicules agricoles à moteur.", type: "acces" },
  { code: "B9e",  categorie: "interdiction", nom: "Accès interdit aux voitures à bras",           description: "Interdit l'accès aux voitures à bras (sauf exceptions).", type: "acces" },
  { code: "B9f",  categorie: "interdiction", nom: "Accès interdit aux véhicules de transport en commun", description: "Interdit l'accès aux véhicules de transport en commun de personnes.", type: "acces" },
  { code: "B9g",  categorie: "interdiction", nom: "Accès interdit aux cyclomoteurs",              description: "Interdit l'accès aux cyclomoteurs.", type: "acces" },
  { code: "B9h",  categorie: "interdiction", nom: "Accès interdit aux motocyclettes",             description: "Interdit l'accès aux motocyclettes et motocyclettes légères.", type: "acces" },
  { code: "B9i",  categorie: "interdiction", nom: "Accès interdit aux véhicules avec caravane",   description: "Interdit l'accès aux véhicules tractant une caravane ou remorque de plus de 250 kg dont le PTRA ne dépasse pas 3,5 t.", type: "acces" },

  // Gabarit et limitation
  { code: "B10a", categorie: "interdiction", nom: "Longueur maximale",                            description: "Interdit l'accès aux véhicules dont la longueur dépasse la valeur indiquée.", type: "gabarit" },
  { code: "B11",  categorie: "interdiction", nom: "Largeur maximale",                             description: "Interdit l'accès aux véhicules dont la largeur (chargement compris) dépasse la valeur indiquée.", type: "gabarit" },
  { code: "B12",  categorie: "interdiction", nom: "Hauteur maximale",                             description: "Interdit l'accès aux véhicules dont la hauteur (chargement compris) dépasse la valeur indiquée.", type: "gabarit" },
  { code: "B13",  categorie: "interdiction", nom: "Poids total maximal autorisé",                 description: "Interdit l'accès aux véhicules dont le poids total autorisé en charge dépasse la valeur indiquée.", type: "gabarit" },
  { code: "B13a", categorie: "interdiction", nom: "Poids maximal par essieu",                     description: "Interdit l'accès aux véhicules pesant sur un essieu plus que la valeur indiquée.", type: "gabarit" },
  { code: "B14",  categorie: "interdiction", nom: "Vitesse maximale autorisée",                   description: "Interdit de dépasser la vitesse indiquée (en km/h).", type: "vitesse" },
  { code: "B15",  categorie: "interdiction", nom: "Cédez le passage à la circulation en sens inverse", description: "Passage étroit : cédez le passage aux véhicules venant en sens inverse.", type: "priorite" },
  { code: "B16",  categorie: "interdiction", nom: "Signaux sonores interdits",                    description: "Interdit l'usage de l'avertisseur sonore (klaxon), sauf danger immédiat.", type: "conduite" },
  { code: "B17",  categorie: "interdiction", nom: "Intervalle minimal obligatoire",               description: "Interdit aux véhicules de circuler sans maintenir entre eux un intervalle au moins égal au nombre indiqué.", type: "conduite" },
  { code: "B18a", categorie: "interdiction", nom: "Accès interdit aux véhicules transportant des explosifs", description: "Interdit l'accès aux véhicules transportant des marchandises explosives ou facilement inflammables.", type: "acces" },
  { code: "B18b", categorie: "interdiction", nom: "Accès interdit aux véhicules transportant des polluants", description: "Interdit l'accès aux véhicules transportant des marchandises susceptibles de polluer les eaux.", type: "acces" },
  { code: "B18c", categorie: "interdiction", nom: "Accès interdit aux véhicules transportant des matières dangereuses", description: "Interdit l'accès aux véhicules transportant des marchandises dangereuses au sens de l'arrêté ADR.", type: "acces" },
  { code: "B19",  categorie: "interdiction", nom: "Autres interdictions",                         description: "Autre interdiction dont la nature est indiquée par une inscription sur le panneau.", type: "divers" },

  // Obligations (ronds bleus)
  { code: "B21-1",  categorie: "obligation", nom: "Tourner à droite obligatoire (avant le panneau)", description: "Oblige à tourner à droite avant le panneau.", type: "direction" },
  { code: "B21-2",  categorie: "obligation", nom: "Tourner à gauche obligatoire (avant le panneau)", description: "Oblige à tourner à gauche avant le panneau.", type: "direction" },
  { code: "B21a1",  categorie: "obligation", nom: "Contournement obligatoire par la droite",      description: "Oblige à contourner l'obstacle par la droite.", type: "direction" },
  { code: "B21a2",  categorie: "obligation", nom: "Contournement obligatoire par la gauche",      description: "Oblige à contourner l'obstacle par la gauche.", type: "direction" },
  { code: "B21b",   categorie: "obligation", nom: "Direction obligatoire : tout droit",           description: "Oblige à aller tout droit à la prochaine intersection.", type: "direction" },
  { code: "B21c1",  categorie: "obligation", nom: "Direction obligatoire : à droite",             description: "Oblige à tourner à droite à la prochaine intersection.", type: "direction" },
  { code: "B21c2",  categorie: "obligation", nom: "Direction obligatoire : à gauche",             description: "Oblige à tourner à gauche à la prochaine intersection.", type: "direction" },
  { code: "B21d1",  categorie: "obligation", nom: "Direction obligatoire : tout droit ou à droite", description: "Oblige à aller tout droit ou à tourner à droite à la prochaine intersection.", type: "direction" },
  { code: "B21d2",  categorie: "obligation", nom: "Direction obligatoire : tout droit ou à gauche", description: "Oblige à aller tout droit ou à tourner à gauche à la prochaine intersection.", type: "direction" },
  { code: "B21e",   categorie: "obligation", nom: "Direction obligatoire : à droite ou à gauche", description: "Oblige à tourner à droite ou à gauche à la prochaine intersection.", type: "direction" },
  { code: "B22a",   categorie: "obligation", nom: "Piste ou bande cyclable obligatoire",          description: "Piste ou bande obligatoire pour les cycles sans side-car ni remorque.", type: "piste" },
  { code: "B22b",   categorie: "obligation", nom: "Chemin obligatoire pour piétons",              description: "Chemin obligatoire pour les piétons.", type: "piste" },
  { code: "B22c",   categorie: "obligation", nom: "Chemin obligatoire pour cavaliers",            description: "Chemin obligatoire pour les cavaliers.", type: "piste" },
  { code: "B25",    categorie: "obligation", nom: "Vitesse minimale obligatoire",                 description: "Oblige à circuler à une vitesse au moins égale à la valeur indiquée (en km/h).", type: "vitesse" },
  { code: "B26",    categorie: "obligation", nom: "Chaînes à neige obligatoires",                 description: "Oblige à équiper d'chaînes à neige au moins deux roues motrices.", type: "conduite" },
  { code: "B27a",   categorie: "obligation", nom: "Voie réservée aux transports en commun",       description: "Voie réservée aux véhicules des services réguliers de transport en commun.", type: "voie" },
  { code: "B27b",   categorie: "obligation", nom: "Voie réservée aux tramways",                   description: "Voie réservée aux tramways.", type: "voie" },
  { code: "B29",    categorie: "obligation", nom: "Autres obligations",                           description: "Autre obligation dont la nature est mentionnée par une inscription sur le panneau.", type: "divers" },
  { code: "B30",    categorie: "obligation", nom: "Entrée en zone 30",                            description: "Signale l'entrée dans une zone à vitesse limitée à 30 km/h.", type: "zone" },

  // Fins de prescription (panneau barré)
  { code: "B31",  categorie: "fin_obligation", nom: "Fin de toutes les interdictions",            description: "Signale la fin de toutes les interdictions précédemment signalées aux véhicules en mouvement.", type: "divers" },
  { code: "B33",  categorie: "fin_obligation", nom: "Fin de limitation de vitesse",               description: "Signale la fin de la limitation de vitesse imposée par le panneau B14.", type: "vitesse" },
  { code: "B34",  categorie: "fin_obligation", nom: "Fin d'interdiction de dépasser",             description: "Signale la fin de l'interdiction de dépasser notifiée par le panneau B3.", type: "depassement" },
  { code: "B34a", categorie: "fin_obligation", nom: "Fin d'interdiction de dépasser pour les PL", description: "Signale la fin de l'interdiction de dépasser pour les poids lourds (B3a).", type: "depassement" },
  { code: "B35",  categorie: "fin_obligation", nom: "Fin d'interdiction des signaux sonores",     description: "Signale la fin de l'interdiction de l'usage de l'avertisseur sonore.", type: "conduite" },
  { code: "B39",  categorie: "fin_obligation", nom: "Fin d'interdiction (autre)",                 description: "Fin d'une interdiction dont la nature est indiquée sur le panneau.", type: "divers" },
  { code: "B40",  categorie: "fin_obligation", nom: "Fin de piste ou bande cyclable obligatoire", description: "Signale la fin de la piste ou bande cyclable obligatoire.", type: "piste" },
  { code: "B41",  categorie: "fin_obligation", nom: "Fin de chemin obligatoire pour piétons",     description: "Signale la fin du chemin obligatoire pour piétons.", type: "piste" },
  { code: "B42",  categorie: "fin_obligation", nom: "Fin de chemin obligatoire pour cavaliers",   description: "Signale la fin du chemin obligatoire pour cavaliers.", type: "piste" },
  { code: "B43",  categorie: "fin_obligation", nom: "Fin de vitesse minimale obligatoire",        description: "Signale la fin de l'obligation de vitesse minimale.", type: "vitesse" },
  { code: "B44",  categorie: "fin_obligation", nom: "Fin d'obligation des chaînes à neige",       description: "Signale la fin de l'obligation d'utiliser des chaînes à neige.", type: "conduite" },
  { code: "B45",  categorie: "fin_obligation", nom: "Fin de voie réservée aux transports en commun", description: "Signale la fin de la voie réservée aux véhicules de transport en commun.", type: "voie" },
  { code: "B49",  categorie: "fin_obligation", nom: "Fin d'obligation (autre)",                   description: "Fin d'une obligation dont la nature est mentionnée sur le panneau.", type: "divers" },
  { code: "B50a", categorie: "fin_obligation", nom: "Sortie de zone à stationnement interdit",    description: "Signale la sortie d'une zone à stationnement interdit.", type: "stationnement" },
  { code: "B50b", categorie: "fin_obligation", nom: "Sortie de zone à stationnement unilatéral alterné", description: "Sortie de zone à stationnement unilatéral à alternance semi-mensuelle.", type: "stationnement" },
  { code: "B50c", categorie: "fin_obligation", nom: "Sortie de zone à stationnement limité (disque)", description: "Sortie de zone à stationnement de durée limitée avec contrôle par disque.", type: "stationnement" },
  { code: "B50d", categorie: "fin_obligation", nom: "Sortie de zone à stationnement payant",      description: "Sortie de zone à stationnement payant.", type: "stationnement" },
  { code: "B50e", categorie: "fin_obligation", nom: "Sortie de zone à stationnement unilatéral alterné et limité", description: "Sortie de zone à stationnement unilatéral à alternance semi-mensuelle et à durée limitée.", type: "stationnement" },
  { code: "B51",  categorie: "fin_obligation", nom: "Sortie de zone 30",                          description: "Signale la sortie d'une zone à vitesse limitée à 30 km/h.", type: "zone" },
  { code: "B52",  categorie: "obligation",     nom: "Entrée en zone de rencontre",                description: "Signale l'entrée dans une zone de rencontre : vitesse max 20 km/h, piétons prioritaires.", type: "zone" },
  { code: "B53",  categorie: "fin_obligation", nom: "Sortie de zone de rencontre",                description: "Signale la sortie d'une zone de rencontre.", type: "zone" },
  { code: "B54",  categorie: "obligation",     nom: "Entrée d'aire piétonne",                     description: "Signale l'entrée dans une aire piétonne. Accès interdit aux véhicules sauf exceptions.", type: "zone" },
  { code: "B55",  categorie: "fin_obligation", nom: "Sortie d'aire piétonne",                     description: "Signale la sortie d'une aire piétonne.", type: "zone" },

  // ── FAMILLE C : INDICATION ────────────────────────────────────────

  { code: "C1a",  categorie: "indication", nom: "Parc de stationnement",                          description: "Indique un lieu aménagé pour le stationnement.", type: "stationnement" },
  { code: "C1b",  categorie: "indication", nom: "Stationnement gratuit à durée limitée (disque)", description: "Lieu aménagé pour le stationnement gratuit à durée limitée avec contrôle par disque.", type: "stationnement" },
  { code: "C1c",  categorie: "indication", nom: "Stationnement payant",                           description: "Lieu aménagé pour le stationnement payant.", type: "stationnement" },
  { code: "C3",   categorie: "indication", nom: "Risque d'incendie",                              description: "Signale un risque d'incendie (forêt, végétation sèche…).", type: "divers" },
  { code: "C4a",  categorie: "indication", nom: "Vitesse conseillée",                             description: "Indique la vitesse à laquelle il est conseillé de circuler si les conditions le permettent.", type: "vitesse" },
  { code: "C4b",  categorie: "indication", nom: "Fin de vitesse conseillée",                      description: "Signale la fin de la vitesse conseillée.", type: "vitesse" },
  { code: "C5",   categorie: "indication", nom: "Station de taxis",                               description: "Station de taxis. L'arrêt et le stationnement y sont réservés aux taxis en service.", type: "stationnement" },
  { code: "C6",   categorie: "indication", nom: "Arrêt d'autobus",                                description: "Arrêt d'autobus. Le stationnement et l'arrêt des autres véhicules y sont interdits.", type: "stationnement" },
  { code: "C8",   categorie: "indication", nom: "Emplacement d'arrêt d'urgence",                  description: "Emplacement d'arrêt d'urgence réservé aux arrêts d'urgence sur l'accotement.", type: "divers" },
  { code: "C12",  categorie: "indication", nom: "Circulation à sens unique",                      description: "Indique que la circulation est à sens unique dans le sens de la flèche.", type: "direction" },
  { code: "C13a", categorie: "indication", nom: "Impasse",                                        description: "Signale une impasse (voie sans issue).", type: "information" },
  { code: "C13b", categorie: "indication", nom: "Présignalisation d'une impasse",                 description: "Annonce une impasse à venir.", type: "information" },
  { code: "C14",  categorie: "indication", nom: "Praticabilité d'une section de route",           description: "Signale qu'une section de route est ouverte ou fermée à la circulation, et précise les conditions d'équipement éventuelles.", type: "divers" },
  { code: "C18",  categorie: "indication", nom: "Priorité par rapport au sens inverse",           description: "Indique que vous avez la priorité par rapport à la circulation venant en sens inverse (passage étroit).", type: "priorite" },
  { code: "C20a", categorie: "indication", nom: "Passage pour piétons",                           description: "Signale un passage pour piétons.", type: "piétons" },
  { code: "C20c", categorie: "indication", nom: "Traversée de tramways",                          description: "Signale une traversée de voies de tramways.", type: "tramway" },
  { code: "C23",  categorie: "indication", nom: "Stationnement réglementé pour caravanes",        description: "Signale un stationnement réglementé pour les caravanes et autocaravanes.", type: "stationnement" },
  { code: "C24a", categorie: "indication", nom: "Conditions particulières de circulation par voie", description: "Indique les conditions particulières de circulation par voie sur la route suivie (nombre de voies, sens, affectation).", type: "voie" },
  { code: "C24b", categorie: "indication", nom: "Voies affectées (présignalisation intersection)", description: "Indique les voies affectées à l'approche d'une intersection.", type: "voie" },
  { code: "C24c", categorie: "indication", nom: "Conditions particulières sur voie embranchée",   description: "Indique les conditions particulières de circulation sur la route embranchée.", type: "voie" },
  { code: "C25a", categorie: "indication", nom: "Limites de vitesse à la frontière",              description: "Indication aux frontières des limites de vitesse sur le territoire français.", type: "vitesse" },
  { code: "C25b", categorie: "indication", nom: "Rappel des limites de vitesse sur autoroute",    description: "Rappel des limites de vitesse applicables sur autoroute.", type: "vitesse" },
  { code: "C26a", categorie: "indication", nom: "Voie de détresse à droite",                      description: "Signale une voie de détresse à droite (pour arrêter un véhicule dont les freins ont lâché).", type: "voie" },
  { code: "C26b", categorie: "indication", nom: "Voie de détresse à gauche",                      description: "Signale une voie de détresse à gauche.", type: "voie" },
  { code: "C27",  categorie: "indication", nom: "Surélévation de chaussée",                       description: "Signale une surélévation de chaussée (dos-d'âne, ralentisseur).", type: "relief" },
  { code: "C28",  categorie: "indication", nom: "Réduction du nombre de voies",                   description: "Signale une réduction du nombre de voies sur une route à chaussées séparées.", type: "voie" },
  { code: "C29a", categorie: "indication", nom: "Présignalisation d'un créneau de dépassement",   description: "Présignalisation d'un créneau de dépassement ou d'une section à chaussées séparées.", type: "voie" },
  { code: "C29b", categorie: "indication", nom: "Créneau de dépassement (2 voies dans un sens)",  description: "Créneau de dépassement à trois voies : deux voies dans un sens, une dans l'autre.", type: "voie" },
  { code: "C29c", categorie: "indication", nom: "Créneau de dépassement (2 voies dans l'autre sens)", description: "Section de route à trois voies : une voie dans un sens, deux dans l'autre.", type: "voie" },
  { code: "C30",  categorie: "indication", nom: "Fin de créneau de dépassement",                  description: "Signale la fin d'un créneau de dépassement à trois voies.", type: "voie" },
  { code: "C50",  categorie: "indication", nom: "Indications diverses",                           description: "Panneau d'indication diverse.", type: "divers" },
  { code: "C62",  categorie: "indication", nom: "Présignalisation d'une borne de retrait de ticket de péage", description: "Présignalisation d'une borne de retrait de ticket de péage.", type: "peage" },
  { code: "C64a", categorie: "indication", nom: "Péage : paiement auprès d'un péagiste",          description: "La voie est tenue par un péagiste.", type: "peage" },
  { code: "C64b", categorie: "indication", nom: "Péage : paiement par carte bancaire",            description: "La voie accepte le paiement par carte bancaire.", type: "peage" },
  { code: "C64c", categorie: "indication", nom: "Péage : paiement automatique par pièces",        description: "La voie est équipée d'un système de paiement automatique par pièces.", type: "peage" },
  { code: "C64d", categorie: "indication", nom: "Péage : paiement par abonnement",                description: "La voie est réservée aux usagers abonnés.", type: "peage" },
  { code: "C107", categorie: "indication", nom: "Route à accès réglementé",                       description: "Annonce le début d'une route à accès réglementé (règles similaires à l'autoroute, vitesse max 110 km/h).", type: "route" },
  { code: "C108", categorie: "indication", nom: "Fin de route à accès réglementé",                description: "Signale la fin d'une section de route à accès réglementé.", type: "route" },
  { code: "C111", categorie: "indication", nom: "Entrée d'un tunnel",                             description: "Signale l'entrée d'un tunnel. Demi-tour, arrêt et stationnement interdits. Feux de croisement obligatoires.", type: "ouvrage" },
  { code: "C112", categorie: "indication", nom: "Sortie de tunnel",                               description: "Signale la sortie du tunnel. Fin des prescriptions du C111.", type: "ouvrage" },
  { code: "C113", categorie: "indication", nom: "Piste ou bande cyclable conseillée",             description: "Piste ou bande cyclable conseillée et réservée aux cycles à deux ou trois roues.", type: "piste" },
  { code: "C114", categorie: "indication", nom: "Fin de piste ou bande cyclable conseillée",      description: "Fin de la piste ou bande cyclable conseillée (C113).", type: "piste" },
  { code: "C115", categorie: "indication", nom: "Voie verte",                                     description: "Voie verte réservée à la circulation des piétons et des véhicules non motorisés.", type: "piste" },
  { code: "C116", categorie: "indication", nom: "Fin de voie verte",                              description: "Fin de la voie verte.", type: "piste" },
  { code: "C117", categorie: "indication", nom: "Présignalisation tunnel – marchandises dangereuses", description: "Présignalisation d'une section comportant un tunnel dont l'accès est interdit à certains véhicules transportant des marchandises dangereuses.", type: "ouvrage" },
  { code: "C207", categorie: "indication", nom: "Début d'une section d'autoroute",                description: "Signale le début d'une section d'autoroute et l'application des règles particulières de circulation.", type: "route" },
  { code: "C208", categorie: "indication", nom: "Fin d'une section d'autoroute",                  description: "Signale la fin de la section d'autoroute. Les règles particulières cessent de s'appliquer.", type: "route" },

  // ── FAMILLE CE : ÉQUIPEMENTS ET SERVICES ─────────────────────────

  { code: "CE1",   categorie: "service", nom: "Poste de secours",                           description: "Indique la présence d'un poste de secours.", type: "service" },
  { code: "CE2a",  categorie: "service", nom: "Poste d'appel d'urgence",                    description: "Indique la présence d'un poste d'appel d'urgence.", type: "service" },
  { code: "CE2b",  categorie: "service", nom: "Cabine téléphonique publique",               description: "Indique la présence d'une cabine téléphonique publique.", type: "service" },
  { code: "CE3a",  categorie: "service", nom: "Informations touristiques",                  description: "Indique des informations relatives aux services ou activités touristiques.", type: "service" },
  { code: "CE3b",  categorie: "service", nom: "Relais d'information service",               description: "Panneau d'information service faisant partie d'un relais d'information service.", type: "service" },
  { code: "CE4a",  categorie: "service", nom: "Terrain de camping pour tentes",             description: "Indique un terrain de camping pour tentes.", type: "service" },
  { code: "CE4b",  categorie: "service", nom: "Terrain de camping pour caravanes",          description: "Indique un terrain de camping pour caravanes et autocaravanes.", type: "service" },
  { code: "CE4c",  categorie: "service", nom: "Terrain de camping mixte",                   description: "Indique un terrain de camping pour tentes, caravanes et autocaravanes.", type: "service" },
  { code: "CE5a",  categorie: "service", nom: "Auberge de jeunesse",                        description: "Indique la présence d'une auberge de jeunesse.", type: "service" },
  { code: "CE5b",  categorie: "service", nom: "Chambre d'hôtes ou gîte",                   description: "Indique la présence d'une chambre d'hôtes ou d'un gîte.", type: "service" },
  { code: "CE6a",  categorie: "service", nom: "Point de départ d'un itinéraire pédestre",  description: "Indique un point de départ d'itinéraire pédestre.", type: "service" },
  { code: "CE6b",  categorie: "service", nom: "Point de départ d'un circuit de ski de fond", description: "Indique un point de départ d'un circuit de ski de fond.", type: "service" },
  { code: "CE7",   categorie: "service", nom: "Aire de pique-nique",                        description: "Indique un emplacement pour pique-nique.", type: "service" },
  { code: "CE8",   categorie: "service", nom: "Gare auto/train",                            description: "Indique une gare auto/train (ferroutage).", type: "service" },
  { code: "CE10",  categorie: "service", nom: "Embarcadère",                               description: "Indique un embarcadère (bac, ferry…).", type: "service" },
  { code: "CE12",  categorie: "service", nom: "Toilettes publiques",                        description: "Indique des toilettes ouvertes au public.", type: "service" },
  { code: "CE14",  categorie: "service", nom: "Installations accessibles aux personnes handicapées", description: "Indique des installations accessibles aux personnes à mobilité réduite.", type: "service" },
  { code: "CE15a", categorie: "service", nom: "Station-service ouverte 24h/24",             description: "Poste de distribution de carburant ouvert 7j/7 et 24h/24.", type: "service" },
  { code: "CE15c", categorie: "service", nom: "Station-service GPL ouverte 24h/24",         description: "Poste de distribution de carburant ouvert 24h/24 assurant également le ravitaillement en GPL.", type: "service" },
  { code: "CE15e", categorie: "service", nom: "Station-service (marque) ouverte 24h/24",   description: "Marque du poste de distribution de carburant ouvert 7j/7 et 24h/24.", type: "service" },
  { code: "CE15f", categorie: "service", nom: "Station-service (marque) GPL ouverte 24h/24", description: "Marque du poste de distribution de carburant ouvert 24h/24 assurant également le GPL.", type: "service" },
  { code: "CE16",  categorie: "service", nom: "Restaurant ouvert 7j/7",                    description: "Restaurant ouvert 7 jours sur 7.", type: "service" },
  { code: "CE17",  categorie: "service", nom: "Hôtel ou motel ouvert 7j/7",                description: "Hôtel ou motel ouvert 7 jours sur 7.", type: "service" },
  { code: "CE18",  categorie: "service", nom: "Café ou collations ouvert 7j/7",            description: "Débit de boissons ou établissement proposant des collations ouvert 7 jours sur 7.", type: "service" },
  { code: "CE19",  categorie: "service", nom: "Mise à l'eau d'embarcations légères",       description: "Emplacement de mise à l'eau d'embarcations légères.", type: "service" },
  { code: "CE20a", categorie: "service", nom: "Gare de téléphérique",                      description: "Indique une gare de téléphérique.", type: "service" },
  { code: "CE20b", categorie: "service", nom: "Télésiège ou télécabine",                   description: "Indique un point de départ d'un télésiège ou d'une télécabine.", type: "service" },
  { code: "CE21",  categorie: "service", nom: "Point de vue",                              description: "Indique un point de vue remarquable.", type: "service" },
  { code: "CE22",  categorie: "service", nom: "Fréquence radio d'information routière",    description: "Fréquence d'émission d'une station de radiodiffusion dédiée aux informations sur la circulation.", type: "service" },
  { code: "CE23",  categorie: "service", nom: "Jeux d'enfants",                            description: "Indique un emplacement de jeux pour enfants.", type: "service" },
  { code: "CE24",  categorie: "service", nom: "Station de vidange pour caravanes",         description: "Station de vidange pour caravanes, autocaravanes et cars.", type: "service" },
  { code: "CE25",  categorie: "service", nom: "Distributeur de billets de banque",         description: "Indique la présence d'un distributeur de billets de banque.", type: "service" },
  { code: "CE26",  categorie: "service", nom: "Station de gonflage gratuite",              description: "Station de gonflage hors station-service, dont l'usage est gratuit.", type: "service" },
  { code: "CE27",  categorie: "service", nom: "Point de détente",                          description: "Indique un point de détente.", type: "service" },
  { code: "CE28",  categorie: "service", nom: "Poste de dépannage",                        description: "Indique la présence d'un poste de dépannage.", type: "service" },
  { code: "CE29",  categorie: "service", nom: "Moyen de lutte contre l'incendie",          description: "Indique la présence d'un moyen de lutte contre l'incendie.", type: "service" },
  { code: "CE30a", categorie: "service", nom: "Issue de secours (vers la droite)",         description: "Indique une issue de secours vers la droite (tunnels).", type: "service" },
  { code: "CE30b", categorie: "service", nom: "Issue de secours (vers la gauche)",         description: "Indique une issue de secours vers la gauche (tunnels).", type: "service" },
  { code: "CE50",  categorie: "service", nom: "Installations ou services divers",          description: "Panneau indiquant des installations ou services divers non couverts par les autres panneaux CE.", type: "service" },

  // ── FAMILLE E / EB : LOCALISATION ────────────────────────────────

  { code: "EB10", categorie: "localisation", nom: "Entrée d'agglomération",    description: "Signale l'entrée dans une agglomération. La vitesse est limitée à 50 km/h sauf indication contraire.", type: "localisation" },
  { code: "EB20", categorie: "localisation", nom: "Sortie d'agglomération",    description: "Signale la sortie d'une agglomération. La limite de 50 km/h cesse de s'appliquer.", type: "localisation" },
  { code: "E31",  categorie: "localisation", nom: "Localisation (lieu traversé)", description: "Localisation de tous les lieux traversés par la route pour lesquels il n'existe pas de panneau spécifique.", type: "localisation" },
  { code: "E32",  categorie: "localisation", nom: "Localisation d'un cours d'eau", description: "Signale la présence d'un cours d'eau.", type: "localisation" },
  { code: "E33a", categorie: "localisation", nom: "Localisation d'un parc naturel", description: "Localisation d'un parc national, parc naturel régional, réserve naturelle ou terrain du Conservatoire du littoral.", type: "localisation" },
  { code: "E33b", categorie: "localisation", nom: "Appartenance à un parc naturel", description: "Indique qu'une commune appartient à un parc national ou parc naturel régional.", type: "localisation" },
  { code: "E36",  categorie: "localisation", nom: "Localisation d'une région ou d'un département", description: "Signale l'entrée dans une région administrative ou un département.", type: "localisation" },

  // ── PANNEAUX SI : SIGNALISATION AVANCÉE DE DIRECTION INTERDITE ───

  { code: "SI1a", categorie: "indication", nom: "Direction interdite aux véhicules de marchandises",           description: "Signalisation avancée d'une direction interdite aux véhicules affectés au transport de marchandises.", type: "divers" },
  { code: "SI1b", categorie: "indication", nom: "Direction interdite aux PL (poids précisé)",                  description: "Signalisation avancée d'une direction interdite aux PL dont le PTAC dépasse le nombre indiqué.", type: "divers" },
  { code: "SI2",  categorie: "indication", nom: "Direction interdite aux cycles",                              description: "Signalisation avancée d'une direction interdite aux cycles.", type: "divers" },
  { code: "SI3",  categorie: "indication", nom: "Direction interdite aux véhicules de transport en commun",    description: "Signalisation avancée d'une direction interdite aux véhicules de transport en commun.", type: "divers" },
  { code: "SI4",  categorie: "indication", nom: "Direction interdite aux cyclomoteurs",                        description: "Signalisation avancée d'une direction interdite aux cyclomoteurs.", type: "divers" },
  { code: "SI5",  categorie: "indication", nom: "Direction interdite aux véhicules longs",                     description: "Signalisation avancée d'une direction interdite aux véhicules dont la longueur dépasse le nombre indiqué.", type: "divers" },
  { code: "SI6",  categorie: "indication", nom: "Direction interdite aux véhicules larges",                    description: "Signalisation avancée d'une direction interdite aux véhicules dont la largeur dépasse le nombre indiqué.", type: "divers" },
  { code: "SI7",  categorie: "indication", nom: "Direction interdite aux véhicules hauts",                     description: "Signalisation avancée d'une direction interdite aux véhicules dont la hauteur dépasse le nombre indiqué.", type: "divers" },
  { code: "SI8",  categorie: "indication", nom: "Direction interdite aux véhicules lourds",                    description: "Signalisation avancée d'une direction interdite aux véhicules dont le PTAC dépasse le nombre indiqué.", type: "divers" },
  { code: "SI9",  categorie: "indication", nom: "Direction interdite aux véhicules (essieu lourd)",            description: "Signalisation avancée d'une direction interdite aux véhicules pesant sur un essieu plus que le nombre indiqué.", type: "divers" },
  { code: "SI10", categorie: "indication", nom: "Direction interdite aux véhicules transportant des explosifs", description: "Signalisation avancée d'une direction interdite aux véhicules transportant des marchandises explosives.", type: "divers" },
  { code: "SI11", categorie: "indication", nom: "Direction interdite aux véhicules transportant des polluants", description: "Signalisation avancée d'une direction interdite aux véhicules transportant des marchandises polluant les eaux.", type: "divers" },
  { code: "SI12", categorie: "indication", nom: "Direction interdite aux véhicules transportant des matières dangereuses", description: "Signalisation avancée d'une direction interdite aux véhicules transportant des marchandises dangereuses.", type: "divers" },
  { code: "SI13", categorie: "indication", nom: "Direction interdite aux motocyclettes",                       description: "Signalisation avancée d'une direction interdite aux motocyclettes.", type: "divers" },
  { code: "SI14", categorie: "indication", nom: "Direction interdite aux véhicules avec caravane",             description: "Signalisation avancée d'une direction interdite aux véhicules tractant une caravane ou remorque >250 kg.", type: "divers" },

  // ── PANNEAUX SC : DIRECTION CONSEILLÉE ───────────────────────────

  { code: "SC1a", categorie: "indication", nom: "Direction conseillée aux véhicules de marchandises",          description: "Indique une direction conseillée aux véhicules affectés au transport de marchandises.", type: "divers" },
  { code: "SC1b", categorie: "indication", nom: "Direction conseillée aux PL (poids précisé)",                 description: "Indique une direction conseillée aux PL dont le PTAC dépasse le nombre indiqué.", type: "divers" },
  { code: "SC2",  categorie: "indication", nom: "Direction conseillée aux cycles",                             description: "Indique une direction conseillée aux cycles.", type: "divers" },
  { code: "SC3",  categorie: "indication", nom: "Direction conseillée aux véhicules de transport en commun",   description: "Indique une direction conseillée aux véhicules de transport en commun.", type: "divers" },
  { code: "SC4",  categorie: "indication", nom: "Direction conseillée aux cyclomoteurs",                       description: "Indique une direction conseillée aux cyclomoteurs.", type: "divers" },

  // ── PANNEAUX SE : AUTOROUTE ───────────────────────────────────────

  { code: "SE2b", categorie: "indication", nom: "Identification d'un échangeur (sortie à droite)",  description: "Permet d'identifier ou de localiser un échangeur pour les sorties situées à droite.", type: "route" },
  { code: "SE2c", categorie: "indication", nom: "Identification d'un échangeur (sortie à gauche)",  description: "Permet d'identifier ou de localiser un échangeur pour les sorties exceptionnellement situées à gauche.", type: "route" },
  { code: "SE3",  categorie: "indication", nom: "Bifurcation autoroutière",                         description: "Permet de signaler une bifurcation autoroutière.", type: "route" },

];

export default panneauxData;
